#!/bin/bash

set -e -o pipefail

script_dir=$(dirname "$(readlink -f "$0")")

if [ ! -d ~/.ssh/sockets ]; then
    mkdir -p ~/.ssh/sockets
fi
   
if [ -z $QWRAP_IP ]; then
    echo "Environment variable QWRAP_IP not set"
    exit 1
fi

ssh -F "$script_dir/ssh_config" $QWRAP_IP qstat "$@"
